{"CVE Code": "CVE-2019-14853", "Description": "An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2019-14853", "Vulnerability Categories": "Denial of service", "Affected Products": "\nPython-ecdsa Project\u00bbPython-ecdsaVersions  before (<) 0.13.3cpe:2.3:a:python-ecdsa_project:python-ecdsa:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.36% Probability of exploitation activity in the next 30 days\n~ 72 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.29%  0.36%  +0.07 \n 2  2024-11-19  0.20%  0.29%  +0.09 \n 3  2023-10-01  0.20%  0.20%  -0.01 \n 4  2023-09-15  0.17%  0.20%  +0.03 \n 5  2023-03-07  1.02%  0.17%  -0.85 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-391 Unchecked Error Condition", "CWE_link": "/cwe-details/391/Unchecked-Error-Condition.html"}, {"CWE_ID": "CWE-755 Improper Handling of Exceptional Conditions", "CWE_link": "/cwe-details/755/Improper-Handling-of-Exceptional-Conditions.html"}], "Reference": [{"ref_link": "https://seclists.org/bugtraq/2019/Dec/33", "ref_desc": "Bugtraq: [SECURITY] [DSA 4588-1] python-ecdsa security update", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3", "ref_desc": "Release ecdsa 0.13.3 \u00b7 warner/python-ecdsa \u00b7 GitHubRelease NotesCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/CflJsefpnY0hXuHir-nLvOUpOvk.html"}, {"ref_link": "https://www.debian.org/security/2019/dsa-4588", "ref_desc": "Debian -- Security Information -- DSA-4588-1 python-ecdsa", "ref_cve_link": "N/A"}, {"ref_link": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853", "ref_desc": "1758704 \u2013 (CVE-2019-14853) CVE-2019-14853 python-ecdsa: Unexpected and undocumented exceptions during signature decodingIssue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}]}