{"CVE Code": "CVE-2022-35993", "Description": "TensorFlow is an open source platform for machine learning. When `SetSize` receives an input `set_shape` that is not a 1D tensor, it gives a `CHECK` fails that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit cf70b79d2662c0d3c6af74583641e345fc939467. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2022-35993", "Vulnerability Categories": "Denial of service", "Affected Products": "\nGoogle\u00bbTensorflowVersions  from including (>=) 2.8.0andbefore (<) 2.8.1cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflowVersions  before (<) 2.7.2cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflowVersions  from including (>=) 2.9.0andbefore (<) 2.9.1cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflow\u00bbVersion:2.10UpdateRC1cpe:2.3:a:google:tensorflow:2.10:rc1:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflow\u00bbVersion:2.10UpdateRC2cpe:2.3:a:google:tensorflow:2.10:rc2:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflow\u00bbVersion:2.10UpdateRC3cpe:2.3:a:google:tensorflow:2.10:rc3:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflow\u00bbVersion:2.10UpdateRC0cpe:2.3:a:google:tensorflow:2.10:rc0:*:*:*:*:*:*Matching versions", "EPSS Score": "0.08% Probability of exploitation activity in the next 30 days\n~ 34 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-04-08  0.08%  0.08%  +0.00 \n 2  2023-10-19  0.07%  0.08%  +0.01 \n 3  2023-09-23  0.06%  0.07%  +0.02 \n 4  2023-08-17  0.05%  0.06%  +0.01 \n 5  2023-03-07  0.89%  0.05%  -0.84 ", "CVSS Scores": "7.5", "CWE": [{"CWE_ID": "CWE-617 Reachable Assertion", "CWE_link": "/cwe-details/617/Reachable-Assertion.html"}], "Reference": [{"ref_link": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-wq6q-6m32-9rv9", "ref_desc": "`CHECK` fail in `SetSize` \u00b7 Advisory \u00b7 tensorflow/tensorflow \u00b7 GitHubThird Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/tensorflow/tensorflow/commit/cf70b79d2662c0d3c6af74583641e345fc939467", "ref_desc": "Fix tf.raw_ops.SetSize vulnerability with invalid input arg specifyin\u2026 \u00b7 tensorflow/tensorflow@cf70b79 \u00b7 GitHubPatch;Third Party Advisory", "ref_cve_link": "N/A"}]}