{"CVE Code": "CVE-2021-29532", "Description": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can force accesses outside the bounds of heap allocated arrays by passing in invalid tensor values to `tf.raw_ops.RaggedCross`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/efea03b38fb8d3b81762237dc85e579cc5fc6e87/tensorflow/core/kernels/ragged_cross_op.cc#L456-L487) lacks validation for the user supplied arguments. Each of the above branches call a helper function after accessing array elements via a `*_list[next_*]` pattern, followed by incrementing the `next_*` index. However, as there is no validation that the `next_*` values are in the valid range for the corresponding `*_list` arrays, this results in heap OOB reads. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2021-29532", "Vulnerability Categories": "N/A", "Affected Products": "\nGoogle\u00bbTensorflowVersions  from including (>=) 2.3.0andbefore (<) 2.3.3cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflowVersions  before (<) 2.1.4cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflowVersions  from including (>=) 2.2.0andbefore (<) 2.2.3cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflowVersions  from including (>=) 2.4.0andbefore (<) 2.4.2cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.04% Probability of exploitation activity in the next 30 days\n~ 5 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.05%  0.04%  -0.01 \n 2  2023-03-07  0.89%  0.05%  -0.84 ", "CVSS Scores": "3.6", "CWE": [{"CWE_ID": "CWE-125 Out-of-bounds Read", "CWE_link": "/cwe-details/125/Out-of-bounds-Read.html"}], "Reference": [{"ref_link": "https://github.com/tensorflow/tensorflow/commit/44b7f486c0143f68b56c34e2d01e146ee445134a", "ref_desc": "Fix out of bounds read in `ragged_cross_op.cc`. \u00b7 tensorflow/tensorflow@44b7f48 \u00b7 GitHubPatch;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-j47f-4232-hvv8", "ref_desc": "Heap out of bounds read in `RaggedCross` \u00b7 Advisory \u00b7 tensorflow/tensorflow \u00b7 GitHubExploit;Patch;Third Party Advisory", "ref_cve_link": "N/A"}]}