{"CVE Code": "CVE-2024-27351", "Description": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2024-27351", "Vulnerability Categories": "Denial of service", "Affected Products": "N/A", "EPSS Score": "0.04% Probability of exploitation activity in the next 30 days\n~ 10 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n Could not find any EPSS score change records for this CVE ", "CVSS Scores": "5.3", "CWE": [{"CWE_ID": "CWE-1333 Inefficient Regular Expression Complexity", "CWE_link": "/cwe-details/1333/Inefficient-Regular-Expression-Complexity.html"}], "Reference": [{"ref_link": "https://groups.google.com/forum/#%21forum/django-announce", "ref_desc": "Sign in - Google AccountsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/2XtVUiFb8mqajovfjsvRevCjbJU.html"}, {"ref_link": "https://docs.djangoproject.com/en/5.0/releases/security/", "ref_desc": "Archive of security issues | Django documentation | DjangoCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/3iv94-6G-57WbNIQ03zosOscdEk.html"}, {"ref_link": "https://www.djangoproject.com/weblog/2024/mar/04/security-releases/", "ref_desc": "Django security releases issued: 5.0.3, 4.2.11, and 3.2.25 | Weblog | Django", "ref_cve_link": "N/A"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/D2JIRXEDP4ZET5KFMAPPYSK663Q52NEX/", "ref_desc": "[SECURITY] Fedora 40 Update: python-django-4.2.11-2.fc40 - package-announce - Fedora Mailing-ListsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/gH6J4d5dvHSzj7ntY7J0rjLf-vI.html"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SN2PLJGYSAAG5KUVIUFJYKD3BLQ4OSN6/", "ref_desc": "[SECURITY] Fedora 39 Update: python-django-4.2.11-2.fc39 - package-announce - Fedora Mailing-ListsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/p6Ayg2F3ciioLvBMoTZ3yFEKQ0Q.html"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZQJOMNRMVPCN5WMIZ7YSX5LQ7IR2NY4D/", "ref_desc": "[SECURITY] Fedora 38 Update: python-django3-3.2.25-2.fc38 - package-announce - Fedora Mailing-ListsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/S1ubR8LDEHsUwYp_yB5o2aX2jPc.html"}, {"ref_link": "http://www.openwall.com/lists/oss-security/2024/03/04/1", "ref_desc": "oss-security - Django: CVE-2024-27351: Potential regular expression denial-of-service in django.utils.text.Truncator.words()CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/vxgYj9L6uIjrBTisDTSYDhh7uYk.html"}]}