{"CVE Code": "CVE-2019-15032", "Description": "Pydio 6.0.8 mishandles error reporting when a directory allows unauthenticated uploads, and the remote-upload option is used with the http://localhost:22 URL. The attacker can obtain sensitive information such as the name of the user who created that directory and other internal server information.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2019-15032", "Vulnerability Categories": "N/A", "Affected Products": "\nPydio\u00bbPydio\u00bbVersion:6.0.8cpe:2.3:a:pydio:pydio:6.0.8:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.24% Probability of exploitation activity in the next 30 days\n~ 64 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.22%  0.24%  +0.02 \n 2  2024-09-12  0.16%  0.22%  +0.06 \n 3  2023-03-07  0.95%  0.16%  -0.79 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-209 Generation of Error Message Containing Sensitive Information", "CWE_link": "/cwe-details/209/Generation-of-Error-Message-Containing-Sensitive-Information.html"}], "Reference": [{"ref_link": "https://sourceforge.net/projects/ajaxplorer/files/pydio/stable-channel/", "ref_desc": "Pydio Cells - Browse /pydio/stable-channel at SourceForge.netRelease NotesCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/_dcckAeax31BVgCFEfT5MbQkKsE.html"}, {"ref_link": "https://pydio.com", "ref_desc": "Pydio | Enterprise File Sharing & Sync PlatformProductCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/EZrM6OQXpKYcdzjBNupEkxUEBB4.html"}, {"ref_link": "https://heitorgouvea.me/2019/09/17/CVE-2019-15032", "ref_desc": "CVE-2019-15032 - Username Leak via Improper Error Handling on Pydio CommunityExploit;Third Party Advisory", "ref_cve_link": "N/A"}]}