{"CVE Code": "CVE-2024-31580", "Description": "PyTorch before v2.2.0 was discovered to contain a heap buffer overflow vulnerability in the component /runtime/vararg_functions.cpp. This vulnerability allows attackers to cause a Denial of Service (DoS) via a crafted input.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2024-31580", "Vulnerability Categories": "Overflow;Denial of service", "Affected Products": "N/A", "EPSS Score": "0.04% Probability of exploitation activity in the next 30 days\n~ 9 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n Could not find any EPSS score change records for this CVE ", "CVSS Scores": "N/A", "CWE": [{"CWE_ID": "CWE-122 Heap-based Buffer Overflow", "CWE_link": "/cwe-details/122/Heap-based-Buffer-Overflow.html"}], "Reference": [{"ref_link": "https://gist.github.com/1047524396/038c78f2f007345e6f497698ace2aa3d", "ref_desc": "CVE-2024-31580 \u00b7 GitHub", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/pytorch/pytorch/commit/b5c3a17c2c207ebefcb85043f0cf94be9b2fef81", "ref_desc": "[fuzzing result][fuzz_torch_jit_lite_interpreter] read-heap-buffer-ov\u2026 \u00b7 pytorch/pytorch@b5c3a17 \u00b7 GitHub", "ref_cve_link": "N/A"}]}