{"CVE Code": "CVE-2021-20285", "Description": "A flaw was found in upx canPack in p_lx_elf.cpp in UPX 3.96. This flaw allows attackers to cause a denial of service (SEGV or buffer overflow and application crash) or possibly have unspecified other impacts via a crafted ELF. The highest threat from this vulnerability is to system availability.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2021-20285", "Vulnerability Categories": "Overflow;Memory Corruption;Denial of service", "Affected Products": "\nUpx Project\u00bbUPX\u00bbVersion:3.96cpe:2.3:a:upx_project:upx:3.96:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.10% Probability of exploitation activity in the next 30 days\n~ 44 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.07%  0.10%  +0.03 \n 2  2023-12-10  0.07%  0.07%  +0.00 \n 3  2023-03-07  0.89%  0.07%  -0.82 ", "CVSS Scores": "8.3", "CWE": [{"CWE_ID": "CWE-119 Improper Restriction of Operations within the Bounds of a Memory Buffer", "CWE_link": "/cwe-details/119/Improper-Restriction-of-Operations-within-the-Bounds-of-a-Me.html"}, {"CWE_ID": "CWE-787 Out-of-bounds Write", "CWE_link": "/cwe-details/787/Out-of-bounds-Write.html"}], "Reference": [{"ref_link": "https://github.com/upx/upx/issues/421", "ref_desc": "canPack@p_lx_elf.cpp:2571 BufferOverflow (both latest release version and devel version) \u00b7 Issue #421 \u00b7 upx/upx \u00b7 GitHubExploit;Issue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://bugzilla.redhat.com/show_bug.cgi?id=1937787", "ref_desc": "1937787 \u2013 (CVE-2021-20285) CVE-2021-20285 upx: Illegal memory access in canPack function in p_lx_elf.cppIssue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}]}