{"CVE Code": "CVE-2023-39661", "Description": "An issue in pandas-ai v.0.9.1 and before allows a remote attacker to execute arbitrary code via the _is_jailbreak function.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2023-39661", "Vulnerability Categories": "Execute code", "Affected Products": "\nGabrieleventuri\u00bbPandasai\u00bbForPythonVersions  up to, including, (<=) 0.9.1cpe:2.3:a:gabrieleventuri:pandasai:*:*:*:*:*:python:*:*Matching versions", "EPSS Score": "0.45% Probability of exploitation activity in the next 30 days\n~ 75 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-09-16  0.42%  0.45%  +0.02 \n 2  2024-08-21  0.30%  0.42%  +0.12 \n 3  2024-07-15  0.27%  0.30%  +0.03 \n 4  2023-08-23  0.05%  0.27%  +0.23 ", "CVSS Scores": "9.8", "CWE": [{"CWE_ID": "CWE-74 Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')", "CWE_link": "/cwe-details/74/Improper-Neutralization-of-Special-Elements-in-Output-Used-b.html"}], "Reference": [{"ref_link": "https://github.com/gventuri/pandas-ai/issues/410", "ref_desc": "The fix of #issue399 (RCE from prompt) can be bypassed. \u00b7 Issue #410 \u00b7 gventuri/pandas-ai \u00b7 GitHubExploit;Issue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}]}