{"CVE Code": "CVE-2021-3116", "Description": "before_upstream_connection in AuthPlugin in http/proxy/auth.py in proxy.py before 2.3.1 accepts incorrect Proxy-Authorization header data because of a boolean confusion (and versus or).", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2021-3116", "Vulnerability Categories": "N/A", "Affected Products": "\nProxy.py Project\u00bbProxy.pyVersions  before (<) 2.3.1cpe:2.3:a:proxy.py_project:proxy.py:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.18% Probability of exploitation activity in the next 30 days\n~ 55 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.16%  0.18%  +0.02 \n 2  2024-02-16  0.14%  0.16%  +0.02 \n 3  2023-09-27  0.12%  0.14%  +0.02 \n 4  2023-08-18  0.10%  0.12%  +0.02 \n 5  2023-04-05  0.08%  0.10%  +0.02 \n 6  2023-03-07  0.95%  0.08%  -0.87 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-697 Incorrect Comparison", "CWE_link": "/cwe-details/697/Incorrect-Comparison.html"}], "Reference": [{"ref_link": "https://github.com/abhinavsingh/proxy.py/pull/482/commits/9b00093288237f5073c403f2c4f62acfdfa8ed46", "ref_desc": "Fix basic auth condition by abhinavsingh \u00b7 Pull Request #482 \u00b7 abhinavsingh/proxy.py \u00b7 GitHubPatch", "ref_cve_link": "N/A"}, {"ref_link": "https://pypi.org/project/proxy.py/2.3.1/#history", "ref_desc": "proxy.py \u00b7 PyPIProduct", "ref_cve_link": "N/A"}, {"ref_link": "https://cardaci.xyz/advisories/2021/01/10/proxy.py-2.3.0-broken-basic-authentication/", "ref_desc": "proxy.py 2.3.0 \u2014 Broken basic authenticationExploit;Third Party Advisory", "ref_cve_link": "N/A"}]}