{"CVE Code": "CVE-2022-23833", "Description": "An issue was discovered in MultiPartParser in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2. Passing certain inputs to multipart forms could result in an infinite loop when parsing files.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2022-23833", "Vulnerability Categories": "N/A", "Affected Products": "\nDebian\u00bbDebian Linux\u00bbVersion:11.0cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:*Matching versions\nFedoraproject\u00bbFedora\u00bbVersion:34cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*Matching versions\nFedoraproject\u00bbFedora\u00bbVersion:35cpe:2.3:o:fedoraproject:fedora:35:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjangoVersions  from including (>=) 3.2andbefore (<) 3.2.12cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjangoVersions  from including (>=) 2.2andbefore (<) 2.2.27cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjangoVersions  from including (>=) 4.0andbefore (<) 4.0.2cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "1.36% Probability of exploitation activity in the next 30 days\n~ 86 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  2.07%  1.36%  -0.71 \n 2  2024-12-12  2.91%  2.07%  -0.84 \n 3  2024-10-19  3.00%  2.91%  -0.09 \n 4  2024-09-09  2.55%  3.00%  +0.45 \n 5  2024-08-14  1.83%  2.55%  +0.72 \n 6  2024-04-27  0.92%  1.83%  +0.91 \n 7  2023-11-23  0.70%  0.92%  +0.22 \n 8  2023-11-08  0.59%  0.70%  +0.11 \n 9  2023-09-24  0.50%  0.59%  +0.09 \n 10  2023-09-10  0.61%  0.50%  -0.11 \n 11  2023-08-26  0.63%  0.61%  -0.02 \n 12  2023-07-16  0.67%  0.63%  -0.04 \n 13  2023-05-10  0.85%  0.67%  -0.18 \n 14  2023-03-07  1.11%  0.85%  -0.26 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-835 Loop with Unreachable Exit Condition ('Infinite Loop')", "CWE_link": "/cwe-details/835/Loop-with-Unreachable-Exit-Condition-Infinite-Loop-.html"}], "Reference": [{"ref_link": "https://github.com/django/django/commit/c477b761804984c932704554ad35f78a2e230c6a", "ref_desc": "[2.2.x] Fixed CVE-2022-23833 -- Fixed DoS possiblity in file uploads. \u00b7 django/django@c477b76 \u00b7 GitHub", "ref_cve_link": "N/A"}, {"ref_link": "https://groups.google.com/forum/#%21forum/django-announce", "ref_desc": "Sign in - Google AccountsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/2XtVUiFb8mqajovfjsvRevCjbJU.html"}, {"ref_link": "https://github.com/django/django/commit/f9c7d48fdd6f198a6494a9202f90242f176e4fc9", "ref_desc": "[4.0.x] Fixed CVE-2022-23833 -- Fixed DoS possiblity in file uploads. \u00b7 django/django@f9c7d48 \u00b7 GitHub", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/django/django/commit/d16133568ef9c9b42cb7a08bdf9ff3feec2e5468", "ref_desc": "[3.2.x] Fixed CVE-2022-23833 -- Fixed DoS possiblity in file uploads. \u00b7 django/django@d161335 \u00b7 GitHub", "ref_cve_link": "N/A"}, {"ref_link": "https://www.debian.org/security/2022/dsa-5254", "ref_desc": "Debian -- Security Information -- DSA-5254-1 python-djangoThird Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/j4dLAlJCuXukQTffvyxxw-5vfQA.html"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/", "ref_desc": "[SECURITY] Fedora 35 Update: python-django-3.2.12-1.fc35 - package-announce - Fedora Mailing-ListsMailing List;Vendor AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/juW2Sw4nTw1iZXbf8yl0cx8kaVg.html"}, {"ref_link": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/", "ref_desc": "Django security releases issued: 4.0.2, 3.2.12, and 2.2.27 | Weblog | DjangoPatch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/NjBBWB6kaH6cY4ZhCk7bMhFwr-k.html"}, {"ref_link": "https://docs.djangoproject.com/en/4.0/releases/security/", "ref_desc": "Archive of security issues | Django documentation | DjangoPatch;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/Pf60y_XDHL9_HIYTNQMkekgqf6Q.html"}, {"ref_link": "https://security.netapp.com/advisory/ntap-20220221-0003/", "ref_desc": "February 2022 Django Vulnerabilities in NetApp Products | NetApp Product SecurityThird Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/uEO2I2OKBb6Kx8sbVYGfngZiTNA.html"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/", "ref_desc": "[SECURITY] Fedora 35 Update: python-django-3.2.12-1.fc35 - package-announce - Fedora Mailing-ListsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/uQxhPBWZsYc_N78iyXRVQzkN0H4.html"}, {"ref_link": "https://groups.google.com/forum/#!forum/django-announce", "ref_desc": "django-announce - Google GroupsMailing List;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/z4Ax_GRKW03p_x8l2GiZviF-qAU.html"}]}