{"CVE Code": "CVE-2021-44647", "Description": "Lua v5.4.3 and above are affected by SEGV by type confusion in funcnamefromcode function in ldebug.c which can cause a local denial of service.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2021-44647", "Vulnerability Categories": "Denial of service", "Affected Products": "\nFedoraproject\u00bbFedora\u00bbVersion:34cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*Matching versions\nLUA\u00bbLUA\u00bbVersion:5.4.3cpe:2.3:a:lua:lua:5.4.3:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.04% Probability of exploitation activity in the next 30 days\n~ 6 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2023-03-07  0.95%  0.04%  -0.91 ", "CVSS Scores": "2.1", "CWE": [{"CWE_ID": "CWE-843 Access of Resource Using Incompatible Type ('Type Confusion')", "CWE_link": "/cwe-details/843/Access-of-Resource-Using-Incompatible-Type-Type-Confusion-.html"}], "Reference": [{"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P3EMGAQ5Y6GXJLY4K5DUOOEQT4MZ4J4F/", "ref_desc": "[SECURITY] Fedora 34 Update: lua-5.4.4-1.fc34 - package-announce - Fedora Mailing-ListsMailing List;Third Party AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/d-Th1P1Ye-yeR00nBWPAIC5s6MI.html"}, {"ref_link": "https://security.gentoo.org/glsa/202305-23", "ref_desc": "Lua: Multiple Vulnerabilities (GLSA 202305-23) \u2014 Gentoo securityCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/G5rJ9YPm2yoQlyNdryS3hYY6b0w.html"}, {"ref_link": "https://access.redhat.com/security/cve/cve-2021-44647", "ref_desc": "CVE-2021-44647- Red Hat Customer PortalThird Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "http://lua-users.org/lists/lua-l/2021-11/msg00195.html", "ref_desc": "Crash : SEGV that occurs during error handling that occurs in the __close metamethod of to-be-closed after calling os.exitExploit;Mailing List;Vendor Advisory", "ref_cve_link": "N/A"}, {"ref_link": "http://lua-users.org/lists/lua-l/2021-11/msg00204.html", "ref_desc": "Re: Crash : SEGV that occurs during error handling that occurs in the __close metamethod of to-be-closed after calling os.exitMailing List;Patch;Vendor Advisory", "ref_cve_link": "N/A"}]}