{"CVE Code": "CVE-2021-32285", "Description": "An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2021-32285", "Vulnerability Categories": "Memory Corruption;Denial of service", "Affected Products": "\nCreolabs\u00bbGravityVersions  up to, including, (<=) 0.8.1cpe:2.3:a:creolabs:gravity:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.05% Probability of exploitation activity in the next 30 days\n~ 25 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.06%  0.05%  0.00 \n 2  2024-06-05  0.05%  0.06%  +0.00 \n 3  2024-04-26  0.05%  0.05%  +0.00 \n 4  2023-04-13  0.05%  0.05%  +0.00 \n 5  2023-03-07  0.89%  0.05%  -0.84 ", "CVSS Scores": "4.3", "CWE": [{"CWE_ID": "CWE-476 NULL Pointer Dereference", "CWE_link": "/cwe-details/476/NULL-Pointer-Dereference.html"}], "Reference": [{"ref_link": "https://github.com/marcobambini/gravity/issues/319", "ref_desc": "A Segmentation fault in gravity_core.c:1100:5 \u00b7 Issue #319 \u00b7 marcobambini/gravity \u00b7 GitHubExploit;Issue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}]}