{"CVE Code": "CVE-2015-0221", "Description": "The django.views.static.serve view in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 reads files an entire line at a time, which allows remote attackers to cause a denial of service (memory consumption) via a long line in a file.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2015-0221", "Vulnerability Categories": "Denial of service", "Affected Products": "\nCanonical\u00bbUbuntu Linux\u00bbVersion:14.04    LTSEditioncpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*Matching versions\nCanonical\u00bbUbuntu Linux\u00bbVersion:14.10cpe:2.3:o:canonical:ubuntu_linux:14.10:*:*:*:*:*:*:*Matching versions\nCanonical\u00bbUbuntu Linux\u00bbVersion:12.04  LTSEditioncpe:2.3:o:canonical:ubuntu_linux:12.04:*:lts:*:*:*:*:*Matching versions\nCanonical\u00bbUbuntu Linux\u00bbVersion:10.04  LTSEditioncpe:2.3:o:canonical:ubuntu_linux:10.04:*:lts:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjangoVersions  up to, including, (<=) 1.4.17cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.5cpe:2.3:a:djangoproject:django:1.6.5:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.1cpe:2.3:a:djangoproject:django:1.6.1:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.2cpe:2.3:a:djangoproject:django:1.6.2:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.3cpe:2.3:a:djangoproject:django:1.6.3:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.4cpe:2.3:a:djangoproject:django:1.6.4:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6cpe:2.3:a:djangoproject:django:1.6:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.9cpe:2.3:a:djangoproject:django:1.6.9:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.7cpe:2.3:a:djangoproject:django:1.7:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.6cpe:2.3:a:djangoproject:django:1.6.6:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.7cpe:2.3:a:djangoproject:django:1.6.7:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.6.8cpe:2.3:a:djangoproject:django:1.6.8:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.7.1cpe:2.3:a:djangoproject:django:1.7.1:*:*:*:*:*:*:*Matching versions\nDjangoproject\u00bbDjango\u00bbVersion:1.7.2cpe:2.3:a:djangoproject:django:1.7.2:*:*:*:*:*:*:*Matching versions", "EPSS Score": "9.46% Probability of exploitation activity in the next 30 days\n~ 95 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  10.07%  9.46%  -0.61 \n 2  2024-08-28  11.23%  10.07%  -1.16 \n 3  2024-07-12  11.99%  11.23%  -0.76 \n 4  2023-03-07  3.78%  11.99%  +8.21 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-399", "CWE_link": "/cwe-details/399/cwe.html"}], "Reference": [{"ref_link": "https://lists.fedoraproject.org/pipermail/package-announce/2015-January/148608.html", "ref_desc": "[SECURITY] Fedora 20 Update: python-django14-1.4.18-1.fc20CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/-K6Zx5HbleuF6zNccDAbB2q40Bc.html"}, {"ref_link": "http://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html", "ref_desc": "openSUSE-SU-2015:0643-1: moderate: Security update for python-DjangoCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/i-IuL0lUB48l5jMd7guju_-gVv8.html"}, {"ref_link": "http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html", "ref_desc": "openSUSE-SU-2015:1598-1: moderate: Security update for python-djangoCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/jgyNy914lxLc6mdfin0_fv-Vv-0.html"}, {"ref_link": "https://lists.fedoraproject.org/pipermail/package-announce/2015-January/148485.html", "ref_desc": "[SECURITY] Fedora 21 Update: python-django-1.6.10-1.fc21CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/me0NYREIPmR79uRbHNPLqc9r3RI.html"}, {"ref_link": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:036", "ref_desc": "mandriva.comCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/Nm4MaPSuuy_1-W0_U6iv7uRnyBs.html"}, {"ref_link": "https://www.djangoproject.com/weblog/2015/jan/13/security/", "ref_desc": "Security releases issued | Weblog | DjangoExploit;Patch;Vendor AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/oJK7-aZgUUYrfkMxOqc0x5oC51I.html"}, {"ref_link": "https://lists.fedoraproject.org/pipermail/package-announce/2015-January/148696.html", "ref_desc": "[SECURITY] Fedora 20 Update: python-django-1.6.10-1.fc20CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/sEFqaSRTdRggunGQDhSlGt3R_5s.html"}, {"ref_link": "http://ubuntu.com/usn/usn-2469-1", "ref_desc": "USN-2469-1: Django vulnerabilities | Ubuntu security noticesPatch;Vendor AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/uEt6aobxhCRuQJifn5nkmGRdSvk.html"}, {"ref_link": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:109", "ref_desc": "mandriva.comCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/Ujes8ZH2Ul7VKIHT3G53bJm14DM.html"}, {"ref_link": "http://advisories.mageia.org/MGASA-2015-0026.html", "ref_desc": "Mageia Advisory: MGASA-2015-0026 - Updated python-django and python-django14 packages fix security vulnerabilitiesCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/VBlBtpcoGtz1847E_B-MojbG-nM.html"}]}