{"CVE Code": "CVE-2020-8192", "Description": "A denial of service vulnerability exists in Fastify v2.14.1 and v3.0.0-rc.4 that allows a malicious user to trigger resource exhaustion (when the allErrors option is used) with specially crafted schemas.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2020-8192", "Vulnerability Categories": "Denial of service", "Affected Products": "\nFastify\u00bbFastify\u00bbVersion:2.14.1ForNode.jscpe:2.3:a:fastify:fastify:2.14.1:*:*:*:*:node.js:*:*Matching versions\nFastify\u00bbFastify\u00bbVersion:3.0.0UpdateRC4ForNode.jscpe:2.3:a:fastify:fastify:3.0.0:rc4:*:*:*:node.js:*:*Matching versions", "EPSS Score": "0.06% Probability of exploitation activity in the next 30 days\n~ 26 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.08%  0.06%  -0.02 \n 2  2023-03-07  0.89%  0.08%  -0.81 ", "CVSS Scores": "4.0", "CWE": [{"CWE_ID": "CWE-400 Uncontrolled Resource Consumption", "CWE_link": "/cwe-details/400/Uncontrolled-Resource-Consumption.html"}], "Reference": [{"ref_link": "https://hackerone.com/reports/903521", "ref_desc": "#903521 Fastify uses allErrors: true ajv configuration by default which is susceptible to DoSExploit;Third Party Advisory", "ref_cve_link": "N/A"}]}