{"CVE Code": "CVE-2018-1000872", "Description": "OpenKMIP PyKMIP version All versions before 0.8.0 contains a CWE 399: Resource Management Errors (similar issue to CVE-2015-5262) vulnerability in PyKMIP server that can result in DOS: the server can be made unavailable by one or more clients opening all of the available sockets. This attack appear to be exploitable via A client or clients open sockets with the server and then never close them. This vulnerability appears to have been fixed in 0.8.0.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2018-1000872", "Vulnerability Categories": "Denial of service", "Affected Products": "\nPykmip Project\u00bbPykmipVersions  before (<) 0.8.0cpe:2.3:a:pykmip_project:pykmip:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.09% Probability of exploitation activity in the next 30 days\n~ 40 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.10%  0.09%  -0.01 \n 2  2024-10-29  0.10%  0.10%  +0.00 \n 3  2024-09-17  0.09%  0.10%  +0.01 \n 4  2024-04-25  0.08%  0.09%  +0.00 \n 5  2024-03-15  0.08%  0.08%  +0.01 \n 6  2024-02-09  0.10%  0.08%  -0.02 \n 7  2023-03-07  0.89%  0.10%  -0.79 ", "CVSS Scores": "4.3", "CWE": [{"CWE_ID": "CWE-400 Uncontrolled Resource Consumption", "CWE_link": "/cwe-details/400/Uncontrolled-Resource-Consumption.html"}], "Reference": [{"ref_link": "https://github.com/OpenKMIP/PyKMIP/issues/430", "ref_desc": "No socket timeout may lead to denial of service \u00b7 Issue #430 \u00b7 OpenKMIP/PyKMIP \u00b7 GitHubExploit;Third Party Advisory;Patch", "ref_cve_link": "N/A"}]}